// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportIssue } from "./ImportIssue";

export type AppError = { "kind": "validation", field: string, message: string, } | { "kind": "not_found", entity: string, id: string, } | { "kind": "conflict", message: string, } | { "kind": "database", message: string, } | { "kind": "io", message: string, } | { "kind": "migration", message: string, backupPath: string | null, } | { "kind": "import_invalid", issues: Array<ImportIssue>, } | { "kind": "internal", message: string, };
