// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the application's data actually lives, so the user is never left
 * guessing. Surfaced in Settings and used by the backup tooling.
 */
export type AppInfo = { name: string, version: string, dataDir: string, platform: string, };
