// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";
import type { UndoRecord } from "./UndoRecord";

export type ArchiveResult = { task: Task, undo: UndoRecord, };
