// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One snapshot on disk, as the restore list shows it.
 */
export type BackupInfo = { path: string, fileName: string, 
/**
 * `manual`, `pre-migration-3`, `pre-import`, `pre-delete`, `pre-restore`.
 */
label: string, manual: boolean, sizeBytes: number, 
/**
 * Taken from the filename rather than the filesystem: a copied or restored
 * file carries a new mtime, but the name still says when it was made.
 */
takenAt: number, };
