// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardTask } from "./BoardTask";
import type { Column } from "./Column";
import type { Label } from "./Label";

export type BoardSnapshot = { boardId: string, columns: Array<Column>, 
/**
 * Live tasks only, ordered by column then position. The frontend groups
 * them; the database does not need to send the same column id repeatedly
 * in a nested shape.
 */
tasks: Array<BoardTask>, 
/**
 * Every label in the project, so a card can render its own without a
 * lookup per label.
 */
labels: Array<Label>, 
/**
 * Archived tasks are not sent — the board does not show them — but the
 * count is, so the UI can offer a way in without a second round trip.
 */
archivedCount: number, };
