// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A task plus exactly what a card draws.
 *
 * Subtask counts arrive as scalar subqueries on the task row rather than as a
 * second pass, and label ids as one grouped query for the whole board. Between
 * them that is what keeps a full board load at a fixed number of queries
 * however many cards it holds.
 */
export type BoardTask = { subtaskCount: number, subtasksDone: number, labelIds: Array<string>, 
/**
 * True when at least one file reference was missing at its last check, so
 * a card can flag it without touching the disk.
 */
hasMissingFile: boolean, id: string, projectId: string, boardId: string, columnId: string, 
/**
 * Per-project, human-readable, and never reused — see `take_next_task_number`.
 */
number: number, title: string, description: string, priority: number, 
/**
 * A calendar date, `YYYY-MM-DD`, never an instant. A due date does not move
 * when the user changes timezone, and has no daylight-saving edge case.
 */
dueDate: string | null, estimateMinutes: number | null, position: number, archivedAt: number | null, createdAt: number, updatedAt: number, };
