// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Board = { id: string, projectId: string, name: string, position: number, createdAt: number, updatedAt: number, };
