// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The colour pair used for Atticus's chrome and interactive accents.
 *
 * Kept separate from `ThemePreference`: a palette does not decide whether the
 * workspace is light or dark. Every palette supplies a measured treatment for
 * both, including when the brightness follows the operating system.
 */
export type ColorPalette = "atticus" | "green-twilight" | "wisteria-prussian" | "violet-linen" | "parchment-coral" | "custard-pine" | "laser-gold";
