// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColumnOrder = { columnId: string, 
/**
 * Live task ids, in order, position 0 first.
 */
taskIds: Array<string>, };
