// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Column = { id: string, boardId: string, name: string, 
/**
 * Soft: exceeding it warns, it never blocks a move (US-7 AC3).
 */
wipLimit: number | null, position: number, createdAt: number, updatedAt: number, };
