// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens to the tasks in a column that is being deleted.
 *
 * There is no default. Deleting work silently is the one outcome this type
 * exists to prevent, so the caller has to say which it meant.
 */
export type ColumnDisposition = { "kind": "moveTo", columnId: string, } | { "kind": "deleteTasks" };
