// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The full settings of a column, not a patch.
 *
 * A patch would need to distinguish "leave the WIP limit alone" from "clear
 * it", which in JSON means the difference between an absent key and a null —
 * a distinction that is easy to lose in transit and awkward to type. The
 * settings dialog always submits both fields anyway, so sending both is honest
 * about what the operation does.
 */
export type ColumnSettings = { name: string, wipLimit: number | null, };
