// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stored shape of a column, for round-tripping through an undo token.
 *
 * Distinct from [`Column`] because that one is a read model for the UI and may
 * grow derived fields; this one must stay exactly the set of stored values.
 */
export type ColumnRow = { id: string, boardId: string, name: string, wipLimit: number | null, position: number, createdAt: number, updatedAt: number, };
