// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the user needs to find, inspect, or back up their own data.
 */
export type DatabaseInfo = { path: string | null, sizeBytes: number | null, schemaVersion: number, latestSchemaVersion: number, backupDirectory: string | null, backupCount: number, };
