// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnRow } from "./ColumnRow";
import type { TaskSnapshot } from "./TaskSnapshot";

/**
 * Everything needed to reverse a column deletion.
 */
export type DeletedColumn = { column: ColumnRow, 
/**
 * Tasks that were moved elsewhere, in their original order in this column.
 */
movedTaskIds: Array<string>, 
/**
 * Tasks that were deleted with the column, with their children.
 */
deletedTasks: Array<TaskSnapshot>, };
