// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What deleting a project would destroy. Shown to the user *before* they
 * confirm, with real numbers rather than a vague warning.
 */
export type DeletedCounts = { boards: number, columns: number, tasks: number, subtasks: number, labels: number, };
