// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelRow } from "./LabelRow";

export type DeletedLabel = { label: LabelRow, 
/**
 * Every task that carried it, so an undo restores the links as well as the
 * label itself.
 */
taskIds: Array<string>, };
