// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportTask = { id: string, projectId: string, boardId: string, columnId: string, number: number, title: string, description: string, priority: number, dueDate: string | null, estimateMinutes: number | null, position: number, archivedAt: number | null, createdAt: number, updatedAt: number, };
