// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportLinkRef = { id: string, taskId: string, url: string, position: number, createdAt: number, };
