// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportData } from "./ExportData";

export type ExportDocument = { exportVersion: number, generatedAt: string, app: string, appVersion: string, data: ExportData, };
