// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File references travel as **paths, not contents** (ADR-0006). Restoring on
 * another machine therefore shows honest "missing file" states rather than
 * pretending the bytes came along.
 */
export type ExportFileRef = { id: string, taskId: string, path: string, displayName: string, position: number, createdAt: number, };
