// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportProject = { id: string, name: string, description: string, color: string, keyPrefix: string, nextTaskNumber: number, directoryPath: string | null, position: number, archivedAt: number | null, createdAt: number, updatedAt: number, };
