// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportColumn = { id: string, boardId: string, name: string, wipLimit: number | null, position: number, createdAt: number, updatedAt: number, };
