// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileRef = { id: string, taskId: string, path: string, displayName: string, lastVerifiedAt: number | null, 
/**
 * Whether the path resolved the last time it was checked. Stored, so a
 * board can render a missing file without touching the disk on every frame.
 */
found: boolean, position: number, createdAt: number, };
