// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileRefRow = { id: string, path: string, displayName: string, lastVerifiedAt: number | null, 
/**
 * Whether the path resolved the last time it was checked. Stored rather
 * than recomputed so the board can show a missing file without touching
 * the filesystem on every render.
 */
found: boolean, position: number, createdAt: number, };
