// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportPlan } from "./ImportPlan";

export type ImportResult = { created: ImportPlan, mode: string, };
