// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One problem with an import file, located the way JSON is located.
 */
export type ImportIssue = { 
/**
 * A JSON path into the document, e.g. `data.tasks[3].columnId`.
 */
path: string, message: string, };
