// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stored shape of a label, for round-tripping through an undo token.
 */
export type LabelRow = { id: string, projectId: string, name: string, color: string, createdAt: number, updatedAt: number, };
