// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveResult } from "./MoveResult";
import type { UndoRecord } from "./UndoRecord";

export type MoveOutcome = { result: MoveResult, undo: UndoRecord | null, };
