// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnOrder } from "./ColumnOrder";
import type { Task } from "./Task";

/**
 * Where a task ended up, and the authoritative order of every column the move
 * touched.
 *
 * Both columns are returned rather than just the destination: the source has
 * closed up behind the task, and a frontend that only heard about the
 * destination would keep showing a gap until the next full load.
 */
export type MoveResult = { task: Task, 
/**
 * Whether anything was actually written.
 */
changed: boolean, columns: Array<ColumnOrder>, };
