// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewProject = { name: string, description: string, color: string, 
/**
 * Derived from the name when absent.
 */
keyPrefix?: string, directoryPath?: string, };
