// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The quick composer's input: a title and where to put it.
 *
 * Everything else has a default. Capturing a thought should cost one field.
 */
export type NewTask = { columnId: string, title: string, };
