// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight workspace-index row. Full Markdown bodies and task IDs stay on
 * the project-scoped note read path and are loaded only when an editor opens.
 */
export type NoteIndexItem = { id: string, projectId: string, title: string, excerpt: string, position: number, updatedAt: number, taskCount: number, };
