// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partial update. An absent field means "leave it alone", which is what lets
 * the editor save a title without having to send the whole body back.
 */
export type NotePatch = { title: string | null, body: string | null, };
