// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Note = { id: string, projectId: string, title: string, body: string, 
/**
 * Complete ordered task association set. Every task belongs to this
 * note's project.
 */
taskIds: Array<string>, position: number, createdAt: number, updatedAt: number, };
