// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every field optional: absent means "leave unchanged", which is what makes a
 * patch different from a replacement.
 */
export type ProjectPatch = { name?: string, description?: string, color?: string, keyPrefix?: string, 
/**
 * Absent leaves the path unchanged; an empty string clears it. A dedicated
 * "clear" flag or a double `Option` would both be more faithful, and both
 * would be worse to use from TypeScript for a field whose empty value is
 * already meaningless.
 */
directoryPath: string | null, };
