// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, name: string, description: string, color: string, keyPrefix: string, nextTaskNumber: number, directoryPath: string | null, 
/**
 * Derived, never stored: a directory on an unmounted volume is still a
 * valid setting, so this is a warning for the UI rather than an error.
 */
directoryMissing: boolean, mcpManaged: boolean, position: number, archivedAt: number | null, createdAt: number, updatedAt: number, };
