// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

/**
 * A project is never created without a board, so creation returns both.
 */
export type ProjectCreated = { project: Project, boardId: string, };
