// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A preference with "system" already decided.
 *
 * Distinct from `ThemePreference` on purpose: the window chrome cannot be told
 * to "follow the system", it has to be told which of the two to paint. Having
 * the type refuse to carry "system" is what stops the frontend and the backend
 * resolving it separately and disagreeing.
 */
export type ResolvedTheme = "light" | "dark";
