// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavedFilter = { id: string, projectId: string, name: string, 
/**
 * The frontend's filter object, serialised. Opaque to Rust.
 */
filter: string, position: number, createdAt: number, updatedAt: number, };
