// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchHit = { taskId: string, boardId: string, projectId: string, number: number, title: string, projectName: string, projectKeyPrefix: string, boardName: string, columnName: string, archived: boolean, writable: boolean, excerpt: string, };
