// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Task = { id: string, projectId: string, boardId: string, columnId: string, 
/**
 * Per-project, human-readable, and never reused — see `take_next_task_number`.
 */
number: number, title: string, description: string, priority: number, 
/**
 * A calendar date, `YYYY-MM-DD`, never an instant. A due date does not move
 * when the user changes timezone, and has no daylight-saving edge case.
 */
dueDate: string | null, estimateMinutes: number | null, position: number, archivedAt: number | null, createdAt: number, updatedAt: number, };
