// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileRefRow } from "./FileRefRow";
import type { LinkRefRow } from "./LinkRefRow";
import type { SubtaskRow } from "./SubtaskRow";
import type { Task } from "./Task";

/**
 * A task and every row that `ON DELETE CASCADE` would take with it.
 */
export type TaskSnapshot = { task: Task, subtasks: Array<SubtaskRow>, labelIds: Array<string>, fileRefs: Array<FileRefRow>, linkRefs: Array<LinkRefRow>, noteTaskLinks: Array<{ noteId: string, position: number, createdAt: number, }>, };
