// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileRef } from "./FileRef";
import type { Label } from "./Label";
import type { Subtask } from "./Subtask";
import type { Task } from "./Task";

/**
 * Everything the task editor shows, in one command.
 *
 * One round trip rather than four, and it is also where file references are
 * re-verified — opening the editor is exactly the moment the user is about to
 * look at them, and the only moment worth touching the disk (ADR-0007).
 */
export type TaskDetail = { task: Task, subtasks: Array<Subtask>, labelIds: Array<string>, fileRefs: Array<FileRef>, 
/**
 * The project's labels, so the picker needs no second call.
 */
availableLabels: Array<Label>, };
