// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partial edit of a task.
 *
 * Every field is genuinely optional — `#[ts(optional)]` so an absent key is
 * absent in TypeScript too, rather than a `null` the caller has to spell out.
 * An absent field means "leave it alone".
 *
 * The two nullable fields need a way to say "clear it", which an absent key
 * cannot express, so each has an explicit `clear_` companion. Verbose, but
 * unambiguous in a way that a `null` travelling through three layers is not.
 */
export type TaskPatch = { title?: string, description?: string, priority?: number, dueDate?: string, clearDueDate?: boolean, estimateMinutes?: number, clearEstimate?: boolean, };
