// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UndoToken } from "./UndoToken";

/**
 * The result of an undoable operation: what it did, and how to take it back.
 */
export type UndoRecord = { 
/**
 * What the toast says was done. Produced by the token itself so the
 * sentence and the operation cannot drift apart.
 */
description: string, token: UndoToken, };
