// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeletedColumn } from "./DeletedColumn";
import type { DeletedLabel } from "./DeletedLabel";
import type { TaskSnapshot } from "./TaskSnapshot";

/**
 * A description of how to reverse one operation.
 *
 * Serialisable and handed to the frontend, which stores it against a toast and
 * hands it back. It is never persisted: undo history does not survive a
 * restart, and the interface does not suggest it does.
 */
export type UndoToken = { "kind": "columnDeleted", "value": DeletedColumn } | { "kind": "taskDeleted", "value": TaskSnapshot } | { "kind": "taskArchiveChanged", "value": { taskId: string, wasArchived: boolean, } } | { "kind": "labelDeleted", "value": DeletedLabel } | { "kind": "taskMoved", "value": { taskId: string, fromColumnId: string, fromIndex: number, } };
