// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateStatus = { "state": "idle" } | { "state": "downloading", version: string, downloaded: number, total: number | null, } | { "state": "ready", version: string, };
