/**
 * Builds a realistically populated board, asserts it holds up at three window
 * sizes, and photographs each one into `e2e/artifacts/visual/`.
 *
 * The screenshots are the point as much as the assertions: `docs/visual-review.md`
 * requires states to be looked at, and a state that is regenerated by the suite
 * cannot quietly go stale the way a screenshot taken by hand once does.
 */
import { mkdirSync } from "node:fs";
import { join } from "node:path";

import { ARTIFACT_DIR } from "../wdio.conf.js";
import {
  addTaskTo,
  chooseMenuItem,
  columnNamed,
  createProject,
  fieldLabelled,
  openMenu,
  openTaskMenu,
  waitForAppReady,
} from "../support/app.js";

const VISUAL_DIR = join(ARTIFACT_DIR, "visual");

const WORK: Record<string, string[]> = {
  Backlog: [
    "Design the label picker",
    "Decide on recurring task semantics",
    "Audit focus order across every dialog",
  ],
  Todo: ["Write the migration for the v2 schema", "Replace the placeholder empty state"],
  "In Progress": ["Accessible keyboard drag-and-drop", "Command palette shell"],
  Blocked: [
    // Deliberately long: the card has to stay readable and must not push the
    // column wider than its neighbours.
    "Waiting on the next Tauri release for the file-dialog fix, which also unblocks the attachment work and the reveal-in-Finder command",
  ],
  Done: ["Board read model in three queries", "Undo via inverse operations"],
};

async function shoot(name: string): Promise<void> {
  mkdirSync(VISUAL_DIR, { recursive: true });

  // Cards carry `transition-colors`, so a shot taken immediately after a resize
  // or a theme change catches them part-way and misreports the design. Settling
  // first is the difference between reviewing the interface and reviewing an
  // animation frame.
  await browser.pause(400);

  await browser.saveScreenshot(join(VISUAL_DIR, `${name}.png`));
}

/** Puts the board back at its left edge so every shot starts from the same place. */
async function resetBoardScroll(): Promise<void> {
  await browser.execute(() => {
    const board = document.querySelector("main > div");
    if (board) board.scrollLeft = 0;
  });
}

describe("visual review", () => {
  before(async () => {
    await createProject("Takenkanban");

    for (const [column, titles] of Object.entries(WORK)) {
      for (const title of titles) {
        await addTaskTo(column, title);
      }
    }

    // One column over its limit, so the warning treatment is in every shot.
    await openMenu("Actions for In Progress");
    await chooseMenuItem("Rename and set a limit");
    await fieldLabelled("Work-in-progress limit").setValue("1");
    await $("button=Save changes").click();
    await $('div[role="dialog"]').waitForDisplayed({ reverse: true });
  });

  it("fills a wide window without stretching the columns", async () => {
    await browser.setWindowRect(null, null, 1680, 1000);
    await resetBoardScroll();
    await expect(columnNamed("Done")).toBeDisplayed();
    await shoot("board-wide");
  });

  it("shows the whole board on a laptop window", async () => {
    await browser.setWindowRect(null, null, 1280, 820);
    await resetBoardScroll();
    await expect(columnNamed("Done")).toBeDisplayed();
    await shoot("board-laptop");
  });

  it("stays usable in a narrow window, scrolling the board rather than the page", async () => {
    await browser.setWindowRect(null, null, 900, 700);
    await resetBoardScroll();
    await expect(columnNamed("Backlog")).toBeDisplayed();

    // The board scrolls sideways inside itself. If the document scrolled
    // instead, the sidebar and header would slide off with it.
    const documentOverflows = await browser.execute(
      () => document.documentElement.scrollWidth > document.documentElement.clientWidth,
    );
    expect(documentOverflows).toBe(false);

    await shoot("board-narrow");
  });

  it("keeps a long card readable rather than letting one column grow", async () => {
    await browser.setWindowRect(null, null, 1280, 820);

    const widths = await $$("main section[aria-labelledby]").map((section) =>
      section.getSize("width"),
    );

    expect(widths.length).toBe(5);
    expect(new Set(widths).size).toBe(1);
  });

  it("photographs the delete-column decision", async () => {
    await openMenu("Actions for Blocked");
    await chooseMenuItem("Delete column");

    const dialog = $('[role="alertdialog"]');
    await dialog.waitForDisplayed();
    await shoot("delete-column-dialog");

    await browser.keys("Escape");
    await dialog.waitForDisplayed({ reverse: true });
  });

  it("photographs the task editor, filled in", async () => {
    await browser.setWindowRect(null, null, 1280, 820);
    await resetBoardScroll();

    await openTaskMenu("Accessible keyboard drag-and-drop");
    await chooseMenuItem("Open");
    const dialog = $('div[role="dialog"]');
    await dialog.waitForDisplayed();

    await dialog
      .$('textarea[aria-label="Edit description"]')
      .setValue(
        "Three routes, one command: pointer drag, keyboard drag, and the actions menu.\n\nSee `docs/adr/0005-atomic-drag-persistence.md` for why nothing is written until the drop.",
      );

    for (const step of ["Pointer sensor", "Keyboard sensor", "Menu commands"]) {
      const field = dialog.$('input[aria-label="New subtask"]');
      await field.setValue(step);
      await browser.keys("Enter");
    }
    await dialog.$$('input[type="checkbox"]')[0]?.click();

    await dialog.$('//span[normalize-space(text())="High"]').click();
    await dialog.$("#task-estimate").setValue("3h 30m");

    await dialog.$("button=New label").click();
    await dialog.$('input[aria-label="New label name"]').setValue("Accessibility");
    await dialog.$("button=Add label").click();
    await dialog.$('//label[.//span[normalize-space(text())="Accessibility"]]//input').click();

    await shoot("task-editor");

    await browser.keys("Escape");
    await dialog.waitForDisplayed({ reverse: true });
  });

  it("photographs a card carrying its detail", async () => {
    await resetBoardScroll();
    await shoot("board-with-detail");
  });

  it("photographs a task held mid-drag", async () => {
    await browser.setWindowRect(null, null, 1280, 820);
    await resetBoardScroll();

    const handle = $('button[aria-label="Drag Command palette shell"]');
    await handle.waitForDisplayed();
    await handle.click();
    await browser.keys(" ");
    await browser.keys("ArrowUp");
    await shoot("task-picked-up");

    await browser.keys("Escape");
  });

  it("photographs the command palette", async () => {
    await browser.setWindowRect(null, null, 1280, 820);
    await browser.keys(["Meta", "k"]);

    const input = $('input[aria-label="Search tasks and commands"]');
    await input.waitForDisplayed();
    await input.setValue("keyboard");
    await browser.waitUntil(async () => (await $$('[role="option"]').length) > 0, {
      timeoutMsg: "the palette found nothing to photograph",
    });

    await shoot("command-palette");

    await browser.keys("Escape");
    await input.waitForDisplayed({ reverse: true });
  });

  it("photographs a filtered board", async () => {
    await resetBoardScroll();
    await $('input[aria-label="Filter tasks on this board"]').setValue("drag");

    await browser.waitUntil(
      async () =>
        (await $("button*=Clear")
          .isDisplayed()
          .catch(() => false)) === true,
      { timeoutMsg: "the filter did not take" },
    );
    await shoot("board-filtered");

    await $("button*=Clear").click();
  });

  it("photographs the light theme", async () => {
    await waitForAppReady();
    await $('button[aria-label="Settings"]').click();
    await $('div[role="dialog"]').waitForDisplayed();
    await $("label=Light").click();
    await browser.keys("Escape");
    await $('div[role="dialog"]').waitForDisplayed({ reverse: true });

    await browser.setWindowRect(null, null, 1280, 820);
    await resetBoardScroll();
    await shoot("board-light");
  });
});
