/**
 * Builds a realistically populated board, asserts it holds up at three window
 * sizes, and photographs each one into `e2e/artifacts/visual/`.
 *
 * The screenshots are the point as much as the assertions: `docs/visual-review.md`
 * requires states to be looked at, and a state that is regenerated by the suite
 * cannot quietly go stale the way a screenshot taken by hand once does.
 */
import { mkdirSync } from "node:fs";
import { join } from "node:path";

import { ARTIFACT_DIR } from "../wdio.conf.js";
import {
  addTaskTo,
  chooseMenuItem,
  chooseOption,
  columnNamed,
  createProject,
  dialogNamed,
  expandProject,
  fieldLabelled,
  openMenu,
  openMenuAt,
  openSettings,
  openTaskMenu,
  projectDestination,
  setViewportWidth,
  waitForAppReady,
} from "../support/app.js";

const VISUAL_DIR = join(ARTIFACT_DIR, "visual");

const WORK: Record<string, string[]> = {
  Backlog: [
    "Design the label picker",
    "Decide on recurring task semantics",
    "Audit focus order across every dialog",
  ],
  Todo: ["Write the migration for the v2 schema", "Replace the placeholder empty state"],
  "In Progress": ["Accessible keyboard drag-and-drop", "Command palette shell"],
  Review: [
    // Deliberately long: the card has to stay readable and must not push the
    // column wider than its neighbours.
    "Waiting on the next Tauri release for the file-dialog fix, which also unblocks the attachment work and the reveal-in-Finder command",
  ],
  Done: ["Board read model in three queries", "Undo via inverse operations"],
};

async function shoot(name: string): Promise<void> {
  mkdirSync(VISUAL_DIR, { recursive: true });

  // Cards carry `transition-colors`, so a shot taken immediately after a resize
  // or a theme change catches them part-way and misreports the design. Settling
  // first is the difference between reviewing the interface and reviewing an
  // animation frame.
  await browser.pause(400);

  await browser.saveScreenshot(join(VISUAL_DIR, `${name}.png`));
}

/** Puts the board back at its left edge so every shot starts from the same place. */
async function resetBoardScroll(): Promise<void> {
  await browser.execute(() => {
    const board = document.querySelector("[data-board-scroll]");
    if (board) board.scrollLeft = 0;
  });
}

/** Measures the lane geometry in CSS pixels, after the native resize has settled. */
async function boardGeometry(): Promise<{
  clientWidth: number;
  scrollWidth: number;
  innerLeft: number;
  innerRight: number;
  firstLeft: number;
  lastRight: number;
  widths: number[];
}> {
  return browser.execute(() => {
    const board = document.querySelector<HTMLElement>("[data-board-scroll]");
    if (board === null) throw new Error("The board scroller is missing");

    const columns = Array.from(
      board.querySelectorAll<HTMLElement>(":scope > section[aria-labelledby]"),
    );
    if (columns.length === 0) throw new Error("The board has no measurable columns");

    const boardBox = board.getBoundingClientRect();
    const style = getComputedStyle(board);
    const first = columns[0]?.getBoundingClientRect();
    const last = columns.at(-1)?.getBoundingClientRect();
    if (first === undefined || last === undefined) throw new Error("Column bounds are missing");

    return {
      clientWidth: board.clientWidth,
      scrollWidth: board.scrollWidth,
      innerLeft: boardBox.left + Number.parseFloat(style.paddingLeft),
      innerRight: boardBox.right - Number.parseFloat(style.paddingRight),
      firstLeft: first.left,
      lastRight: last.right,
      widths: columns.map((column) => column.getBoundingClientRect().width),
    };
  });
}

describe("visual review", () => {
  before(async () => {
    await createProject("Takenkanban");

    for (const [column, titles] of Object.entries(WORK)) {
      for (const title of titles) {
        await addTaskTo(column, title);
      }
    }

    // One column over its limit, so the warning treatment is in every shot.
    await openMenu("Actions for In Progress");
    await chooseMenuItem("Rename and set a limit");
    await fieldLabelled("Work-in-progress limit").setValue("1");
    await $("button=Save changes").click();
    await $('div[role="dialog"]').waitForDisplayed({ reverse: true });
  });

  it("fits the complete board across a wide window", async () => {
    await setViewportWidth(1680, 1000);
    await resetBoardScroll();
    await expect(columnNamed("Done")).toBeDisplayed();

    const geometry = await boardGeometry();
    expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.clientWidth + 1);
    expect(Math.abs(geometry.firstLeft - geometry.innerLeft)).toBeLessThanOrEqual(1);
    expect(Math.abs(geometry.lastRight - geometry.innerRight)).toBeLessThanOrEqual(1);
    await shoot("board-wide");
  });

  it("keeps the board readable inside a laptop window", async () => {
    await setViewportWidth(1280, 820);
    await resetBoardScroll();
    await expect(columnNamed("Done")).toBeDisplayed();
    await shoot("board-laptop");
  });

  it("stays usable in a narrow window, scrolling the board rather than the page", async () => {
    // 900 CSS pixels, which is the minimum product-spec §6 supports — and which
    // this test did not previously reach. `setViewportWidth` converts and then
    // proves the viewport landed; see its comment for why that is not pedantry.
    await setViewportWidth(900, 700);
    await resetBoardScroll();
    await expect(columnNamed("Backlog")).toBeDisplayed();

    // The board scrolls sideways inside itself. If the document scrolled
    // instead, the sidebar and header would slide off with it.
    //
    // The assertion names the elements sticking out rather than reporting a
    // boolean. A bare `false` here cost most of a session: it says the document
    // is wider than the window and nothing about which box made it that way,
    // which is the only fact that leads to a fix.
    const overflowing = await browser.execute(() => {
      const limit = document.documentElement.clientWidth;

      // Content inside a horizontal scroller is *supposed* to extend past the
      // viewport — that is the board doing its job. Only boxes that overhang
      // without such an ancestor push the document itself.
      const scrolls = (element: Element) => {
        const overflowX = getComputedStyle(element).overflowX;
        return overflowX === "auto" || overflowX === "scroll";
      };
      const insideAScroller = (element: Element) => {
        for (let parent = element.parentElement; parent !== null; parent = parent.parentElement) {
          if (scrolls(parent)) return true;
        }
        return false;
      };

      return Array.from(document.querySelectorAll("*"))
        .filter((element) => Math.round(element.getBoundingClientRect().right) > limit)
        .filter((element) => !insideAScroller(element))
        .map((element) => {
          const right = Math.round(element.getBoundingClientRect().right);
          // `getAttribute` rather than `className`: on an SVG element the
          // property is an `SVGAnimatedString`, which stringifies to
          // "[object SVGAnimatedString]" and names nothing.
          const classes = (element.getAttribute("class") ?? "").slice(0, 60);
          const name =
            element.getAttribute("aria-label") ?? element.textContent.trim().slice(0, 30);
          return `${element.tagName.toLowerCase()}.${classes} "${name}" right=${String(right)} limit=${String(limit)}`;
        });
    });

    expect(overflowing).toStrictEqual([]);

    const geometry = await boardGeometry();
    expect(geometry.scrollWidth).toBeGreaterThan(geometry.clientWidth);
    expect(geometry.widths.every((width) => width >= 260)).toBe(true);
    expect(new Set(geometry.widths.map(Math.round)).size).toBe(1);

    await shoot("board-narrow");
  });

  it("fits the real columns across a 1920 display without a phantom action lane", async () => {
    await setViewportWidth(1920, 1080);
    await resetBoardScroll();
    await expect(columnNamed("Done")).toBeDisplayed();

    const geometry = await boardGeometry();
    expect(new Set(geometry.widths.map(Math.round)).size).toBe(1);
    expect(geometry.widths[0]).toBeGreaterThanOrEqual(260);
    expect(geometry.widths[0]).toBeLessThanOrEqual(384);
    expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.clientWidth + 1);

    await shoot("board-1920");
  });

  it("uses the extra width at the supplied 2048px reference size", async () => {
    await setViewportWidth(2048, 1080);
    await resetBoardScroll();

    const geometry = await boardGeometry();
    expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.clientWidth + 1);
    expect(Math.abs(geometry.firstLeft - geometry.innerLeft)).toBeLessThanOrEqual(1);
    expect(Math.abs(geometry.lastRight - geometry.innerRight)).toBeLessThanOrEqual(1);
    expect(geometry.widths[0]).toBeGreaterThan(320);

    await shoot("board-2048");
  });

  it("keeps a long card readable rather than letting one column grow", async () => {
    await setViewportWidth(1280, 820);

    const widths = (await boardGeometry()).widths;

    expect(widths.length).toBe(5);
    expect(new Set(widths).size).toBe(1);
  });

  it("photographs the delete-column decision", async () => {
    await openMenu("Actions for Review");
    await chooseMenuItem("Delete column");

    const dialog = $('[role="alertdialog"]');
    await dialog.waitForDisplayed();
    await shoot("delete-column-dialog");

    await browser.keys("Escape");
    await dialog.waitForDisplayed({ reverse: true });
  });

  it("photographs the task editor, filled in", async () => {
    await setViewportWidth(1280, 820);
    await resetBoardScroll();

    await openTaskMenu("Accessible keyboard drag-and-drop");
    await chooseMenuItem("Open");
    const dialog = dialogNamed("Edit task");
    await dialog.waitForDisplayed();

    await dialog
      .$('textarea[aria-label="Edit description"]')
      .setValue(
        "Three routes, one command: pointer drag, keyboard drag, and the actions menu.\n\nSee `docs/adr/0005-atomic-drag-persistence.md` for why nothing is written until the drop.",
      );

    for (const step of ["Pointer sensor", "Keyboard sensor", "Menu commands"]) {
      const field = dialog.$('input[aria-label="Add a new checklist item"]');
      await field.setValue(step);
      await browser.keys("Enter");
    }
    await dialog.$('section[aria-labelledby="checklist-heading"] input[type="checkbox"]').click();

    await openMenuAt("#task-priority");
    await shoot("task-priority-menu");
    await browser.keys("Escape");
    await $('[role="menu"]').waitForDisplayed({ reverse: true });

    await chooseOption("#task-priority", "High");
    await dialog.$("#task-estimate").setValue("3h 30m");

    await dialog.$("#task-due").click();
    const datePicker = $('[role="dialog"][aria-label="Choose due date"]');
    await datePicker.waitForDisplayed();
    await shoot("task-date-picker");
    await browser.keys("Escape");
    await datePicker.waitForDisplayed({ reverse: true });

    await dialog.$("button=Add tag").click();
    await dialog.$('input[aria-label="Tag name"]').setValue("Accessibility");
    await dialog.$("button=Add “Accessibility”").click();
    await dialog.$('button[aria-label="Remove Accessibility"]').waitForDisplayed();

    await shoot("task-editor");

    await setViewportWidth(1920, 1000);
    const focusGeometry = await browser.execute(() => {
      const main = document.querySelector<HTMLElement>("[data-task-editor-main]");
      const rail = document.querySelector<HTMLElement>("[data-task-editor-rail]");
      if (main === null || rail === null) throw new Error("Task editor layout is missing");

      main.scrollTop = 0;
      rail.scrollTop = 0;
      const mainRect = main.getBoundingClientRect();
      const railRect = rail.getBoundingClientRect();

      return {
        viewportWidth: window.innerWidth,
        mainLeft: mainRect.left,
        mainRight: mainRect.right,
        railLeft: railRect.left,
        railRight: railRect.right,
        railWidth: railRect.width,
        documentOverflow: document.documentElement.scrollWidth - window.innerWidth,
      };
    });

    expect(Math.abs(focusGeometry.mainLeft)).toBeLessThanOrEqual(1);
    expect(Math.abs(focusGeometry.mainRight - focusGeometry.railLeft)).toBeLessThanOrEqual(1);
    expect(Math.abs(focusGeometry.railRight - focusGeometry.viewportWidth)).toBeLessThanOrEqual(1);
    expect(focusGeometry.railWidth).toBeGreaterThanOrEqual(340);
    expect(focusGeometry.railWidth).toBeLessThanOrEqual(360);
    expect(focusGeometry.documentOverflow).toBeLessThanOrEqual(1);
    await shoot("task-editor-wide");

    await setViewportWidth(1280, 820);

    await dialog.$("button=Save changes").click();
    await dialog.waitForDisplayed({ reverse: true });
  });

  it("photographs a card carrying its detail", async () => {
    await resetBoardScroll();
    await shoot("board-with-detail");
  });

  it("photographs a task held mid-drag", async () => {
    await setViewportWidth(1280, 820);
    await resetBoardScroll();

    const handle = $('button[aria-label="Drag Command palette shell"]');
    await handle.waitForDisplayed();
    await handle.click();
    await browser.keys(" ");
    await browser.keys("ArrowUp");
    await shoot("task-picked-up");

    await browser.keys("Escape");
  });

  it("photographs the command palette", async () => {
    await setViewportWidth(1280, 820);
    await browser.keys(["Meta", "k"]);

    const input = $('input[aria-label="Search tasks and commands"]');
    await input.waitForDisplayed();
    await input.setValue("keyboard");
    await browser.waitUntil(async () => (await $$('[role="option"]').length) > 0, {
      timeoutMsg: "the palette found nothing to photograph",
    });

    await shoot("command-palette");

    await browser.keys("Escape");
    await input.waitForDisplayed({ reverse: true });
  });

  it("photographs a filtered board", async () => {
    await resetBoardScroll();
    await $('input[aria-label="Filter tasks on this board"]').setValue("drag");

    await browser.waitUntil(
      async () =>
        await $("button*=Clear")
          .isDisplayed()
          .catch(() => false),
      { timeoutMsg: "the filter did not take" },
    );
    await shoot("board-filtered");

    await $("button*=Clear").click();
  });

  it("photographs the full-page notes workspace with its linked work", async () => {
    await setViewportWidth(1680, 940);
    await expandProject("Takenkanban");
    await projectDestination("Takenkanban", "Project Notes").click();
    const notes = dialogNamed("Project Notes");
    await notes.waitForDisplayed();
    await notes.$("h2=Pages").waitForDisplayed();
    await notes.$('button[aria-label="New note"]').click();

    const title = notes.$("#note-title");
    const body = notes.$("#note-body");
    await title.waitForDisplayed();
    await title.setValue("Accessible movement plan");
    await body.setValue(
      "# Objective\n\nMake every movement route feel like one coherent system.\n\n## Working agreement\n\n- Pointer, keyboard, and menu actions share the same transaction.\n- Focus returns to the task after every move.\n\n## Verification\n\n- [x] Board read model\n- [ ] Keyboard announcement pass",
    );

    await openMenuAt('button[aria-label="Link tasks to this note"]');
    const linkedTask = $(
      '//*[@role="menuitemcheckbox"][contains(., "Accessible keyboard drag-and-drop")]',
    );
    await linkedTask.waitForDisplayed();
    await linkedTask.click();
    await browser.keys("Escape");

    await $("h1=Objective").waitForDisplayed({ timeout: 5_000 });
    await shoot("notes-workspace-dark");

    await notes.$('button[aria-label^="Return to "]').click();
    await notes.waitForDisplayed({ reverse: true });
  });

  it("photographs the workspace-wide note index", async () => {
    await $('//nav[@aria-label="Workspace"]//button[normalize-space(.)="All Notes"]').click();

    const notes = dialogNamed("All Notes");
    await notes.waitForDisplayed();
    await notes.$("h1=All notes").waitForDisplayed();
    await notes.$('button[aria-label="Accessible movement plan, Takenkanban"]').waitForDisplayed();
    await shoot("all-notes-dark");

    await notes.$('button[aria-label^="Return to "]').click();
    await notes.waitForDisplayed({ reverse: true });
  });

  it("photographs the settings workspace", async () => {
    await setViewportWidth(1440, 900);
    await openSettings();

    const settings = dialogNamed("Settings");
    await settings.$('button[aria-label="AI access"]').click();
    await expect(settings.$("h2=AI access")).toBeDisplayed();
    await shoot("settings-ai-dark");

    await browser.keys("Escape");
    await settings.waitForDisplayed({ reverse: true });
  });

  it("photographs the light theme", async () => {
    await waitForAppReady();
    await openSettings();
    const settings = dialogNamed("Settings");
    await settings.waitForDisplayed();
    await settings.$('button[aria-label="General"]').click();
    await settings.$('//label[normalize-space(.)="Light"]').click();
    await browser.keys("Escape");
    await settings.waitForDisplayed({ reverse: true });

    await setViewportWidth(1280, 820);
    await resetBoardScroll();
    await shoot("board-light");
  });

  it("photographs the board in greyscale, with every signal still readable", async () => {
    // `design-decisions.md` §3 promises priority, due-date state and a
    // work-in-progress breach each survive without colour. This is that promise
    // photographed: the whole document desaturated, so a reviewer sees what a
    // greyscale display — or a reader who cannot separate these hues — sees.
    //
    // The properties themselves are asserted where they can fail loudly:
    // `src/features/board/greyscale.test.ts` for the encodings, and
    // `board.e2e.ts` for the breach announcement. What is added here is the
    // evidence that they are actually rendered together on one board.
    await setViewportWidth(1280, 820);
    await resetBoardScroll();

    await browser.execute(() => {
      document.documentElement.style.filter = "grayscale(1)";
    });

    // Named, not merely present: with the colour gone these three are the whole
    // of the encoding, so the shot is only worth keeping if they are in it.
    const column = $('//section[.//h3[normalize-space(text())="In Progress"]]');
    await expect(column).toHaveText(expect.stringContaining("2/1"));

    const card = $('//li[.//*[normalize-space(text())="Accessible keyboard drag-and-drop"]]');
    await expect(card).toHaveText(expect.stringContaining("High"));

    await shoot("board-greyscale");

    await browser.execute(() => {
      document.documentElement.style.filter = "";
    });
  });

  it("photographs the daily field report", async () => {
    await $('//button[.//span[normalize-space(.)="Dashboard"]]').click();
    await $("p=Daily field report").waitForDisplayed();
    await shoot("dashboard-light");
  });

  it("photographs the project index", async () => {
    await $('//nav[@aria-label="Breadcrumb"]//button[normalize-space(.)="Projects"]').click();
    await $("h1=My Projects").waitForDisplayed();
    await shoot("projects-light");
  });
});
